#!/bin/bash
#Para ter informações do processado :  fabricante, nome do computador, velocidade,numeros de nucleos e arquitetura...
fabri_can=$(lscpu | grep "Vendor ID" | awk -F: '{print $2}' | xargs) #grep "Vendor ID":filtra a saída do lscpu para encontrar a linha que contém "Vendor ID".
velo_cid=$(cat /proc/cpuinfo | grep "cpu MHz" | awk -F: '{print $2}')
nu_cle=$(lscpu | grep "CPU(s):" | awk -F: '{print $2}' | xargs)
ar_te=$(lscpu | grep "Architecture" | awk -F: '{print $2}' | xargs) #xargs remove espaços desnecessários... 
ram=$(free -m | grep Men | awk '{print $2}') #informações da memoria ram livre  
interface=$(ip route | grep default | awk '{print $5}') #
ip=$(ip -o -f inet addr show enp0s3 | awk '{print $4}')
mask=$(ifconfig enp0s3 | awk '/netmask/ {print $4}')
mac=$(usr/sbin/ip link show $i| awk '/ether/ {print $2}')

echo "----------------------------------------------"
echo -e "\e[1m RELATÓRIO GERENCIAL DO SERVIDOR $(uname -o)\e[0m"
echo "---------------------------------------------"
echo -e "\e[1m 1 - Informações do Processador\e[0m"
echo -e "  - Nome do computador é: \e[1m$(hostname)\e[0m"
echo -e "  - Fabricante: \e[1m$fabri_can\e[0m"
echo -e "  - Velocidade: \e[1m$velo_cid MHz\e[0m"
echo -e "  - Números de Núcleos: \e[1m$nu_cle\e[0m"
echo -e "  - Arquitetura: \e[1m$ar_te\e[0m"

echo ""
echo -e "\e[1m 2 - Memória RAM\e[0m"
echo -e "  - Memória Ram (livre): \e[1m$ram MB\e[0m"

echo ""
echo -e "\e[1m 3 - Informações da Placa de Rede $interface\e[0m"
echo -e "  - IP: \e[1m$ip/$mask\e[0m"
echo -e "  - MAC: \e[1m$mac\e[0m"

echo ""
echo -e "\e[1m 4 - Serviço TCP em Execução\e[0m"
echo "---------------------------------------------"
echo "  - Conexões Internet Ativas (somente servidores)"
echo "---------------------------------------------"
echo -e "\e[1m"
netstat -ltpn | awk 'NR>1 {printf " %-6s %-6s %-15s %-11s %-8s %s\n", $1, $4, $5, $6, $7, $8}'
echo "---------------------------------------------"

